/**
 * pi-prides — Project scaffolding (pure plan generator)
 *
 * `scaffoldPlan` returns the list of files to write; the host performs the
 * actual I/O. Keeping this pure makes it trivially testable.
 */
import type { Clock, ProjectIntent } from "./types.js";

export interface ScaffoldFile {
	path: string;
	content: string;
}

function pridesDoc(i: ProjectIntent): string {
	return `# PRIDES — ${i.name}

> Methodology: **P**rototype → **R**eview → **I**mplement → **D**eploy → **E**xtend → **S**ecure

## Intent
${i.purpose}
${i.stack ? `\nStack: ${i.stack}` : ""}
${i.repository ? `\nRepository: ${i.repository}` : ""}

## Phase gates (summary)
- **R / Review** — human code-review sign-off
- **I / Implement** — unit + e2e tests, linter, dependency audit
- **D / Deploy** — deployment pre-flight check
- **E / Extend** — performance + accessibility budgets
- **S / Secure** — security audit

Run \`/prides status\` to inspect current phase, gates, and heartbeat.
This file is generated by \`prides_scaffold\`.
`;
}

export function scaffoldPlan(
	intent: ProjectIntent,
	now: Clock,
): ScaffoldFile[] {
	const ts = new Date(now()).toISOString();
	const intentJson = `${JSON.stringify(
		{
			name: intent.name,
			purpose: intent.purpose,
			stack: intent.stack ?? null,
			repository: intent.repository ?? null,
			createdAt: ts,
			methodology: "PRIDES",
		},
		null,
		2,
	)}\n`;

	return [
		{ path: ".prides/intent.json", content: intentJson },
		{
			path: ".prides/gates.config.json",
			content: `${JSON.stringify({ note: "Override gate commands per project; see DEFAULT_GATES." }, null, 2)}\n`,
		},
		{
			path: "dev_notes/TASKS.md",
			content:
				"# TASKS\n\n| ID | Task | Status | Phase |\n|----|------|--------|-------|\n",
		},
		{ path: "dev_notes/PROGRESS.md", content: `# PROGRESS\n\nStarted ${ts}\n` },
		{ path: "dev_notes/CHANGELOG.md", content: "# CHANGELOG\n" },
		{
			path: "dev_notes/ARCHITECTURE.md",
			content: "# ARCHITECTURE\n\n> Document the system design here.\n",
		},
		{ path: "PRIDES.md", content: pridesDoc(intent) },
	];
}
